language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
addons:
  code_climate:
    repo_token: 9e29b21ed7c89f601837244578bd8307acfc281d487cd7a5982461b268a7cb97
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
